export {setupNaive} from '@/scripts/plugins/naive'
export {setupNaiveDiscreteApi} from '@/scripts/plugins/naiveDiscreteApi'
export {setupDirectives} from '@/scripts/plugins/directives'
export {setupGlobalProperties} from '@/scripts/plugins/globalProperties'
export {setupTheme} from '@/scripts/plugins/theme'
export {setupLayer} from '@/scripts/plugins/layer'
